site_name: ODE

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://plyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/text-mml-chtml.js

nav:
  - index.md
  - reference.md

